general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Caskaydia Cove Nerd Font Mono" }
bold = { family = "Caskaydia Cove Nerd Font Mono" }
italic = { family = "Caskaydia Cove Nerd Font Mono" }
size = 9

[window]
 padding.x = 14
# padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
