[font]
normal = { family = "SpaceMono Nerd Font", style = "Regular" }
bold = { family = "SpaceMono Nerd Font", style = "Bold" }
italic = { family = "SpaceMono Nerd Font", style = "Italic" }
bold_italic = { family = "SpaceMono Nerd Font", style = "Bold Italic" }
size = 10.0

[window]
opacity = 0.95
blur = true

[selection]
save_to_clipboard = true

[general]
import = [
    "alacritty_kanagawa.yml",
]

