cursor #cad3f5
cursor_text_color #a5adcb

foreground            #cad3f5
background            #24273a
selection_foreground  #24273a
selection_background  #8bd5ca
url_color             #a6da95

color0   #1e2030
color1   #fa8d70
color2   #71da6d
color3   #ffed72
color4   #93cf80
color5   #38642a
color6   #a6da95
color7   #dae4d7
color8   #858d83
color9   #ffb39f
color10  #a9ffa5
color11  #fff3a5
color12  #bfefaf
color13  #d4ffc6
color14  #e3ffda
color15  #fafff8
