foreground              #FFFFFF
background              #010206
selection_foreground    #010206
selection_background    #FFFFFF
cursor                  #B4CCE5 
cursor_text_color       #080808

active_tab_foreground     #010206
active_tab_background     #3D98D2
inactive_tab_foreground   #3D98D2
inactive_tab_background   #010206

# black
color0      #293152
color8      #57628F

# red
color1      #CCE5FF
color9      #AACCF0

# green
color2      #CCE7FF
color10     #AACFF0

# yellow
color3      #CCEBFF
color11     #AAD5F0

# blue
color4      #9AA9E6
color12     #9AA9E6

# magenta
color5      #9AC2E6
color13     #9AC2E6

# cyan
color6      #9AC8E6
color14     #9AC8E6

# white
color7      #CCE5FF
color15     #AACCF0
