foreground              #FFFFFF
background              #2C101D
selection_foreground    #2C101D
selection_background    #FFFFFF
cursor                  #D4CCC7 
cursor_text_color       #080808

active_tab_foreground     #2C101D
active_tab_background     #B1817D
inactive_tab_foreground   #B1817D
inactive_tab_background   #2C101D

# black
color0      #52293C
color8      #8F5771

# red
color1      #FFE0CC
color9      #F0C5AA

# green
color2      #FFCCDC
color10     #F0AAC0

# yellow
color3      #FFD0CC
color11     #F0B0AA

# blue
color4      #E69ABD
color12     #E69ABD

# magenta
color5      #E69AB1
color13     #E69AB1

# cyan
color6      #E6A09A
color14     #E6A09A

# white
color7      #FFE0CC
color15     #F0C5AA
