-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
-- 'thenbe/neotest-playwright',
-- 	keys = {
-- 		{
-- 			'<leader>ta',
-- 			function()
-- 				require('neotest').playwright.attachment()
-- 			end,
-- 			desc = 'Launch test attachment',
-- 		},
-- 	},
