#!/bin/bash

export PATH="$HOME/.config/hypr/scripts/:$PATH"

# Set to true when going directly to a submenu, so we can exit directly
BACK_TO_EXIT=false

back_to() {
  local parent_menu="$1"

  if [[ "$BACK_TO_EXIT" == "true" ]]; then
    exit 0
  elif [[ -n "$parent_menu" ]]; then
    "$parent_menu"
  else
    show_main_menu
  fi
}
6088214819

menu() {
  local prompt="$1"
  local options="$2"
  local extra="$3"
  local preselect="$4"

  read -r -a args <<<"$extra"

  if [[ -n "$preselect" ]]; then
    local index
    index=$(echo -e "$options" | grep -nxF "$preselect" | cut -d: -f1)
    if [[ -n "$index" ]]; then
      args+=("-c" "$index")
    fi
  fi

  echo -e "$options" | launch-walker --dmenu --width 295 --minheight 1 --maxheight 600 -p "$prompt…" "${args[@]}" 2>/dev/null
}

terminal() {
  alacritty -e "$@"
}

present_terminal() {
  launch-floating-terminal-with-presentation $1
}

open_in_editor() {
  notify-send "Editing config file" "$1"
  launch-editor "$1"
}

install_font() {
  present_terminal "echo 'Installing $1...'; sudo pacman -S --noconfirm --needed $2 && sleep 2 && font-set '$3'"
}

install_terminal() {
  present_terminal "install-terminal $1"
}

aur_install() {
  present_terminal "echo 'Installing $1 from AUR...'; yay -S --noconfirm $2"
}

aur_install_and_launch() {
  present_terminal "echo 'Installing $1 from AUR...'; yay -S --noconfirm $2 && setsid gtk-launch $3"
}

show_learn_menu() {
  case $(menu "Learn" "  Keybindings\n  Omarchy\n  Hyprland\n󰣇  Arch\n  Neovim\n󱆃  Bash") in
  *Keybindings*) menu-keybindings ;;
  *Hyprland*) launch-webapp "https://wiki.hypr.land/" ;;
  *Arch*) launch-webapp "https://wiki.archlinux.org/title/Main_page" ;;
  *Bash*) launch-webapp "https://devhints.io/bash" ;;
  *Neovim*) launch-webapp "https://www.lazyvim.org/keymaps" ;;
  *) show_main_menu ;;
  esac
}

show_trigger_menu() {
  case $(menu "Trigger" "  Capture\n  Share\n󰔎  Toggle") in
  *Capture*) show_capture_menu ;;
  *Share*) show_share_menu ;;
  *Toggle*) show_toggle_menu ;;
  *) show_main_menu ;;
  esac
}

show_capture_menu() {
  case $(menu "Capture" "  Screenshot\n  Screenrecord\n󰃉  Color") in
  *Screenshot*) show_screenshot_menu ;;
  *Screenrecord*) show_screenrecord_menu ;;
  *Color*) pkill hyprpicker || hyprpicker -a ;;
  *) show_trigger_menu ;;
  esac
}

show_screenshot_menu() {
  case $(menu "Screenshot" "  Snap with Editing\n  Straight to Clipboard") in
  *Editing*) cmd-screenshot smart ;;
  *Clipboard*) cmd-screenshot smart clipboard ;;
  *) show_capture_menu ;;
  esac
}

show_screenrecord_menu() {
  case $(menu "Screenrecord" "  Region\n  Region + Audio\n  Display\n  Display + Audio\n  Display + Webcam") in
  *"Region + Audio"*) cmd-screenrecord region --with-audio ;;
  *Region*) cmd-screenrecord ;;
  *"Display + Audio"*) cmd-screenrecord output --with-audio ;;
  *"Display + Webcam"*) cmd-screenrecord output --with-audio --with-webcam ;;
  *Display*) cmd-screenrecord output ;;
  *) back_to show_capture_menu ;;
  esac
}

show_share_menu() {
  case $(menu "Share" "  Clipboard\n  File \n  Folder") in
  *Clipboard*) terminal bash -c "cmd-share clipboard" ;;
  *File*) terminal bash -c "cmd-share file" ;;
  *Folder*) terminal bash -c "cmd-share folder" ;;
  *) back_to show_trigger_menu ;;
  esac
}

show_toggle_menu() {
  case $(menu "Toggle" "󱄄  Screensaver\n󰔎  Nightlight\n󱫖  Idle Lock\n󰍜  Top Bar") in
  *Screensaver*) toggle-screensaver ;;
  *Nightlight*) toggle-nightlight ;;
  *Idle*) toggle-idle ;;
  *Bar*) toggle-waybar ;;
  *) show_trigger_menu ;;
  esac
}

show_font_menu() {
  theme=$(menu "Font" "$(font-list)" "--width 350" "$(font-current)")
  if [[ "$theme" == "CNCLD" || -z "$theme" ]]; then
    back_to show_style_menu
  else
    font-set "$theme"
  fi
}

show_setup_menu() {
  local options="  Audio\n  Wifi\n󰂯  Bluetooth\n󱐋  Power Profile\n󰍹  Monitors"
  [ -f ~/.config/hypr/bindings.conf ] && options="$options\n  Keybindings"
  [ -f ~/.config/hypr/input.conf ] && options="$options\n  Input"
  options="$options\n  Defaults\n󰱔  DNS\n  Security\n  Config"

  case $(menu "Setup" "$options") in
  *Audio*) $TERMINAL --class=Wiremix -e wiremix ;;
  *Wifi*)
    rfkill unblock wifi
    launch-wifi
    ;;
  *Bluetooth*)
    rfkill unblock bluetooth
    blueberry
    ;;
  *Power*) show_setup_power_menu ;;
  *Monitors*) open_in_editor ~/.config/hypr/monitors.conf ;;
  *Keybindings*) open_in_editor ~/.config/hypr/bindings.conf ;;
  *Input*) open_in_editor ~/.config/hypr/input.conf ;;
  *Defaults*) open_in_editor ~/.config/uwsm/default ;;
  *DNS*) present_terminal setup-dns ;;
  *Security*) show_setup_security_menu ;;
  *Config*) show_setup_config_menu ;;
  *) show_main_menu ;;
  esac
}

show_setup_power_menu() {
  profile=$(menu "Power Profile" "$(powerprofiles-list)" "" "$(powerprofilesctl get)")

  if [[ "$profile" == "CNCLD" || -z "$profile" ]]; then
    back_to show_setup_menu
  else
    powerprofilesctl set "$profile"
  fi
}

show_setup_config_menu() {
  case $(menu "Setup" "  Hyprland\n  Hypridle\n  Hyprlock\n  Hyprsunset\n  Swayosd\n󰌧  Walker\n󰍜  Waybar\n󰞅  XCompose") in
  *Hyprland*) open_in_editor ~/.config/hypr/hyprland.conf ;;
  *Hypridle*) open_in_editor ~/.config/hypr/hypridle.conf && restart-hypridle ;;
  *Hyprlock*) open_in_editor ~/.config/hypr/hyprlock.conf ;;
  *Hyprsunset*) open_in_editor ~/.config/hypr/hyprsunset.conf && restart-hyprsunset ;;
  *Swayosd*) open_in_editor ~/.config/swayosd/config.toml && restart-swayosd ;;
  *Walker*) open_in_editor ~/.config/walker/config.toml && restart-walker ;;
  *Waybar*) open_in_editor ~/.config/waybar/config.jsonc && restart-waybar ;;
  *XCompose*) open_in_editor ~/.XCompose && restart-xcompose ;;
  *) show_main_menu ;;
  esac
}

show_setup_security_menu() {
  case $(menu "Setup" "󰈷  Fingerprint\n  Fido2") in
  *Fingerprint*) present_terminal setup-fingerprint ;;
  *Fido2*) present_terminal setup-fido2 ;;
  *) show_setup_menu ;;
  esac
}

show_install_menu() {
  case $(menu "Install" "󰣇  Package\n󰣇  AUR\n  Web App\n  TUI\n  Service\n  Style\n󰵮  Development\n  Editor\n  Terminal\n󱚤  AI\n󰍲  Windows\n  Gaming") in
  *Package*) terminal pkg-install ;;
  *AUR*) terminal pkg-aur-install ;;
  *Web*) present_terminal webapp-install ;;
  *TUI*) present_terminal tui-install ;;
  *Service*) show_install_service_menu ;;
  *) show_main_menu ;;
  esac
}

show_install_font_menu() {
  case $(menu "Install" "  Meslo LG Mono\n  Fira Code\n  Victor Code\n  Bistream Vera Mono" "--width 350") in
  *Meslo*) install_font "Meslo LG Mono" "ttf-meslo-nerd" "MesloLGL Nerd Font" ;;
  *Fira*) install_font "Fira Code" "ttf-firacode-nerd" "FiraCode Nerd Font" ;;
  *Victor*) install_font "Victor Code" "ttf-victor-mono-nerd" "VictorMono Nerd Font" ;;
  *Bistream*) install_font "Bistream Vera Code" "ttf-bitstream-vera-mono-nerd" "BitstromWera Nerd Font" ;;
  *) show_install_menu ;;
  esac
}

show_remove_menu() {
  case $(menu "Remove" "󰣇  Package\n  Web App\n  TUI\n󰸌  Theme\n󰍲  Windows\n󰈷  Fingerprint\n  Fido2") in
  *Package*) terminal pkg-remove ;;
  *Web*) present_terminal webapp-remove ;;
  *TUI*) present_terminal tui-remove ;;
  *Theme*) present_terminal theme-remove ;;
  *Windows*) present_terminal "windows-vm remove" ;;
  *Fingerprint*) present_terminal "setup-fingerprint --remove" ;;
  *Fido2*) present_terminal "setup-fido2 --remove" ;;
  *) show_main_menu ;;
  esac
}

show_update_process_menu() {
  case $(menu "Restart" "  Hypridle\n  Hyprsunset\n  Swayosd\n󰌧  Walker\n󰍜  Waybar") in
  *Hypridle*) restart-hypridle ;;
  *Hyprsunset*) restart-hyprsunset ;;
  *Swayosd*) restart-swayosd ;;
  *Walker*) restart-walker ;;
  *Waybar*) restart-waybar ;;
  *) show_update_menu ;;
  esac
}

show_update_config_menu() {
  case $(menu "Use default config" "  Hyprland\n  Hypridle\n  Hyprlock\n  Hyprsunset\n󱣴  Plymouth\n  Swayosd\n󰌧  Walker\n󰍜  Waybar") in
  *Hyprland*) present_terminal refresh-hyprland ;;
  *Hypridle*) present_terminal refresh-hypridle ;;
  *Hyprlock*) present_terminal refresh-hyprlock ;;
  *Hyprsunset*) present_terminal refresh-hyprsunset ;;
  *Plymouth*) present_terminal refresh-plymouth ;;
  *Swayosd*) present_terminal refresh-swayosd ;;
  *Walker*) present_terminal refresh-walker ;;
  *Waybar*) present_terminal refresh-waybar ;;
  *) show_update_menu ;;
  esac
}

show_update_hardware_menu() {
  case $(menu "Restart" "  Audio\n󱚾  Wi-Fi\n󰂯  Bluetooth") in
  *Audio*) present_terminal restart-pipewire ;;
  *Wi-Fi*) present_terminal restart-wifi ;;
  *Bluetooth*) present_terminal restart-bluetooth ;;
  *) show_update_menu ;;
  esac
}

show_update_password_menu() {
  case $(menu "Update Password" "  Drive Encryption\n  User") in
  *Drive*) present_terminal drive-set-password ;;
  *User*) present_terminal passwd ;;
  *) show_update_menu ;;
  esac
}

show_system_menu() {
  case $(menu "System" "  Lock\n󱄄  Screensaver\n󰤄  Suspend\n󰜉  Restart\n󰐥  Shutdown\n󰍂  Logout") in
  *Lock*) lock-screen ;;
  *Screensaver*) launch-screensaver force ;;
  *Suspend*) systemctl suspend ;;
  *Restart*) state clear re*-required && systemctl reboot --no-wall ;;
  *Shutdown*) state clear re*-required && systemctl poweroff --no-wall ;;
  *Logout*) hyprctl dispatch exit ;;
  *) back_to show_main_menu ;;
  esac
}

show_main_menu() {
  case $(menu "System" "  Lock\n󱄄  Screensaver\n󰤄  Suspend\n󰜉  Restart\n󰐥  Shutdown\n󰍂  Logout") in
  *Lock*) lock-screen ;;
  *Screensaver*) launch-screensaver force ;;
  *Suspend*) systemctl suspend ;;
  *Restart*) state clear re*-required && systemctl reboot --no-wall ;;
  *Shutdown*) state clear re*-required && systemctl poweroff --no-wall ;;
  *Logout*) hyprctl dispatch exit ;;
  *) exit 0 ;;
  esac
  # go_to_menu "$(menu "Go" "󰀻  Apps \n  System")"
}

go_to_menu() {
  case "${1,,}" in
  *apps*) walker -p "Launch…" ;;
  *system*) show_system_menu ;;
  esac
}

if [[ -n "$1" ]]; then
  BACK_TO_EXIT=true
  go_to_menu "$1"
else
  show_main_menu
fi
