#!/bin/bash

if [[ -z $1 && $1 != "CNCLD" ]]; then
  echo "Usage: omarchy-theme-set <theme-name>"
  exit 1
fi

THEMES_DIR="$HOME/.config/omarchy/themes/"
CURRENT_THEME_DIR="$HOME/.config/omarchy/current/theme"

THEME_NAME=$(echo "$1" | sed -E 's/<[^>]+>//g' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
THEME_PATH="$THEMES_DIR/$THEME_NAME"

# Check if the theme entered exists
if [[ ! -d "$THEME_PATH" ]]; then
  echo "Theme '$THEME_NAME' does not exist in $THEMES_DIR"
  exit 1
fi

# Update theme symlinks
ln -nsf "$THEME_PATH" "$CURRENT_THEME_DIR"

# Change background with theme
~/.config/hypr/scripts/theme-bg-next

# Restart components to apply new theme
if pgrep -x waybar >/dev/null; then
  ~/.config/hypr/scripts/restart-waybar
fi
~/.config/hypr/scripts/restart-swayosd
hyprctl reload
pkill -SIGUSR2 btop
makoctl reload

# Change gnome, browser, vscode, cursor themes
~/.config/hypr/scripts/theme-set-terminal
~/.config/hypr/scripts/theme-set-gnome
~/.config/hypr/scripts/theme-set-browser
~/.config/hypr/scripts/theme-set-vscode
~/.config/hypr/scripts/theme-set-cursor
~/.config/hypr/scripts/theme-set-obsidian

# Call hook on theme set
~/.config/hypr/scripts/hook theme-set "$THEME_NAME"
