-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(a6da95)",
			inactive_border = "rgb(6e738d)",
		},
	},
	group = {
		col = {
			border_active = "rgb(a6da95)",
			border_inactive = "rgb(6e738d)",
			border_locked_active = "rgb(ed8796)",
			border_locked_inactive = "rgb(6e738d)",
		},
		groupbar = {
			col = {
				active = "rgb(a6da95)",
				inactive = "rgb(6e738d)",
				locked_active = "rgb(ed8796)",
				locked_inactive = "rgb(6e738d)",
			},
		},
	},
})
