# Extra autostart processes
# exec-once = uwsm app -- my-service
exec-once = /usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
exec-once = udiskie
exec-once = swaync
exec-once = waybar
