# Extra env variables
# env = MY_GLOBAL_ENV,setting
env = ELECTRON_FORCE_DEVICE_SCALE_FACTOR,1
env = XDG_CURRENT_DESKTOP=Hyprland 
env =  MOZ_ENABLE_WAYLAND=1 
env = XDG_SESSION_TYPE=wayland
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/gcr/ssh 
