exec-once = ags &
exec-once = ~/.azotebg-hyprland
# exec-once=~/.config/hypr/themes/poeisis/scripts/signal.sh
# exec-once = ulauncher --hide-window
# exec-once=systemctl --user import-environment PATH; systemctl --user start ulauncher
# exec-once=systemctl --user enable --now ulauncher
