# Set Themes And Configs #
## Scripts ##
exec-once=$HOME/.config/hypr/autostart
source=~/.config/hypr/keybinds.conf
source=~/.config/hypr/execs.conf

# Monitor Configs
monitor=,preferred,auto,1 # for pluggin in random monitors
monitor=,highrr,auto,1 # prefer high refresh rate for all monitors

input {
    kb_layout=
    kb_variant=ffffff
    kb_model=
    kb_options=compose:rctrl,level3:ralt_switch
    kb_rules=

    follow_mouse=1

    touchpad {
        natural_scroll=yes
        disable_while_typing=true
        scroll_factor=1
    }
}

misc {
    disable_hyprland_logo=true
    animate_mouse_windowdragging=false # this fixes the laggy window movement (source: https://github.com/hyprwm/Hyprland/issues/1753)
    animate_manual_resizes=false # fixes slow resizes
}

general {
    gaps_in = 4
    gaps_out = 5
    gaps_workspaces = 50
    border_size = 1
    col.active_border=rgba(A8C5E6ff) rgba(f1a7e2ff) 45deg
    col.inactive_border=0xff0B0A10
    resize_on_border = true
    no_focus_fallback = true
    layout = dwindle
    apply_sens_to_raw=0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)
    col.nogroup_border=0xff89dceb
    col.nogroup_border_active=0xfff9e2af
}

decoration {
    rounding = 10
    drop_shadow=true
    shadow_range=15
    shadow_render_power=2
    shadow_ignore_window=true
    shadow_offset= 0 4
    col.shadow=0x55000000
    col.shadow_inactive=0x55000000
blur {
    new_optimizations = on
    # rounding=15
    enabled=true
    # size=1 # minimum 1
    # passes=2 # minimum 1, more passes = more resource intensive.
    # Your blur "amount" is blur_size * blur_passes, but high blur_size (over around 5-ish) will produce artifacts.
    # if you want heavy blur, you need to up the blur_passes.
    # the more passes, the more you can up the blur_size without noticing artifacts.
    #
    xray = true
    special = false
    new_optimizations = true
    size = 14
    passes = 4
    brightness = 1
    noise = 0.01
    contrast = 1
    popups = true
    }
}

misc {
    animate_mouse_windowdragging=false # this fixes the laggy window movement (source: https://github.com/hyprwm/Hyprland/issues/1753)
}

animations {
    # Flick0's animations
    enabled=1
    bezier=overshot,0.13,0.99,0.29,1.10
    animation=windows,1,5,overshot,slide
    animation=border,0,10,default
    animation=fade,1,10,default
    animation=workspaces,1,4,default,slide
}

dwindle {
    pseudotile=1 # enable pseudotiling on dwindle
    force_split=0
    preserve_split = true
    # no_gaps_when_only = 1
    smart_split = false
    smart_resizing = false
}

master{
    
}

gestures {
    workspace_swipe=yes
    workspace_swipe_fingers=4
}

# other
windowrule=float,^(nm-connection-editor)$
# floating windows
windowrule=float,title:^(org.gnome.Nautilus New Folder)$
# firefox sharing indicator
# windowrule=nofullscreenrequest,title:^(Firefox — Sharing Indicator)$
windowrule=float,title:^(Bluetooth)$
windowrule=move 100%-650 70,title:^(Bluetooth)$

### some exec-once config ###
# Set Primary Screen
exec=~/.config/hypr/scripts/variables/set_env primary 0

# spamton shimeji
windowrule=float, com-group_finity-mascot-Main
windowrule=noblur, com-group_finity-mascot-Main
windowrule=nofocus, com-group_finity-mascot-Main
windowrule=noshadow, com-group_finity-mascot-Main
windowrule=noborder, com-group_finity-mascot-Main

windowrulev2=noblur,class:^()$,title:^()$

layerrule=noanim, ^(selection)$
layerrule=blur,notifications
layerrule=ignorezero,notifications
