exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(B4CCE5ff) rgba(293D52ff) 45deg
    col.inactive_border = rgba(010206ff) rgba(03437Bff) 45deg
}

group {
    col.border_active = rgba(B4CCE5ff) rgba(293D52ff) 45deg
    col.border_inactive = rgba(010206cc) rgba(03437Bcc) 45deg
    col.border_locked_active = rgba(141312ff) rgba(080808ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
